name: first gh-action file
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        python-vesrion: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 
    - uses: actions/setup-python@v5
   
  #triggering the python version
      with:
        python-version: ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest gh-cicd.py 
  

        
